import { get, post, put, del, postChat, getDown, postUpload } from "../../utils/request";



export async function createSessions(data = {}) {
  return post("/api/v1/sessions", data);
}

export async function getSessionsList(page: number, page_size: number, source?: string) {
  const params = new URLSearchParams({ page: String(page), page_size: String(page_size) });
  if (source) {
    params.set("source", source);
  }
  return get(`/api/v1/sessions?${params.toString()}`);
}

export async function pinSession(session_id: string) {
  return post(`/api/v1/sessions/${session_id}/pin`, {});
}

export async function unpinSession(session_id: string) {
  return del(`/api/v1/sessions/${session_id}/pin`);
}

export async function generateSessionsTitle(session_id: string, data: any) {
  return post(`/api/v1/sessions/${session_id}/generate_title`, data);
}

export async function updateSession(session_id: string, data: { title: string; description?: string }) {
  return put(`/api/v1/sessions/${session_id}`, data);
}

export async function knowledgeChat(data: { session_id: string; query: string; }) {
  return postChat(`/api/v1/knowledge-chat/${data.session_id}`, { query: data.query, channel: "web" });
}

// Agent chat with streaming support
export async function agentChat(data: { 
  session_id: string; 
  query: string;
  knowledge_base_ids?: string[];
  agent_enabled: boolean;
}) {
  return postChat(`/api/v1/agent-chat/${data.session_id}`, { 
    query: data.query,
    knowledge_base_ids: data.knowledge_base_ids,
    agent_enabled: data.agent_enabled,
    channel: "web"
  });
}

export async function getMessageList(data: { session_id: string; limit: number, created_at: string }) {
  if (data.created_at) {
    return get(`/api/v1/messages/${data.session_id}/load?before_time=${encodeURIComponent(data.created_at)}&limit=${data.limit}`);
  } else {
    return get(`/api/v1/messages/${data.session_id}/load?limit=${data.limit}`);
  }
}

export async function delSession(session_id: string) {
  return del(`/api/v1/sessions/${session_id}`);
}

export async function batchDelSessions(ids: string[]) {
  return del(`/api/v1/sessions/batch`, { ids });
}

export async function deleteAllSessions() {
  return del(`/api/v1/sessions/batch`, { delete_all: true });
}

export async function getSession(session_id: string) {
  return get(`/api/v1/sessions/${session_id}`);
}

export async function stopSession(session_id: string, message_id: string) {
  return post(`/api/v1/sessions/${session_id}/stop`, { message_id });
}

export async function clearSessionMessages(session_id: string) {
  return del(`/api/v1/sessions/${session_id}/messages`);
}

// ---------------------------------------------------------------------------
// Skill artifacts (files generated by skill scripts during agent turns)
//
// The backend keeps the physical storage path private and indexes each file by
// its position (:index) in the owning assistant message. The list endpoints
// return metadata only — clients must go through downloadArtifact to fetch
// the actual bytes so ownership checks always run server-side.
// ---------------------------------------------------------------------------

export interface ArtifactMeta {
  index: number;
  /**
   * `resource://<handle>` — the artifact's stable identity, and the destination
   * the answer body references. Empty when the deployment runs without a
   * resource catalog, in which case the body references files by name.
   */
  handle?: string;
  file_name: string;
  file_type: string;
  file_size: number;
  source_path: string;
  mod_time: string;
  created_at: string;
}

// listMessageArtifacts returns the artifacts attached to a single assistant
// message. Used by the drawer opened from the message action toolbar.
export async function listMessageArtifacts(session_id: string, message_id: string) {
  return get(
    `/api/v1/sessions/${session_id}/messages/${message_id}/artifacts`,
  );
}

// listSessionArtifacts returns every artifact recorded against the whole
// session, in creation order. Powers "download everything generated in this
// chat" drawers.
export async function listSessionArtifacts(session_id: string) {
  return get(`/api/v1/sessions/${session_id}/artifacts`);
}

// downloadArtifact streams a single artifact's bytes as a Blob so the caller
// can trigger a browser download. A plain `<a href>` cannot be used because
// axios attaches the Bearer token per request; issuing the download via
// `getDown` keeps auth intact and lets the response be turned into an
// object URL.
export async function downloadArtifact(
  session_id: string,
  message_id: string,
  index: number,
): Promise<Blob> {
  return getDown(
    `/api/v1/sessions/${session_id}/messages/${message_id}/artifacts/${index}/download`,
  );
}

// ---------------------------------------------------------------------------
// Session sandbox file browser — CRUD over the workspace bound to a session.
// Paths are sandbox-absolute ("/workspace/..."); the server jails every path
// lexically, so the client never has to sanitise. Downloads use the same
// blob pattern as artifacts because the endpoint needs the Bearer token.
// ---------------------------------------------------------------------------

export interface SandboxFileEntry {
  name: string;
  /** Sandbox-absolute path of the entry, usable in every other verb. */
  path: string;
  /** "file" | "dir" */
  type: string;
  size: number;
  mod_time_unix: number;
}

// listSandboxFiles lists one directory (default /workspace) without recursing.
// 404 means no live sandbox is bound to the session yet.
export async function listSandboxFiles(session_id: string, path = "/workspace") {
  return get(
    `/api/v1/sessions/${session_id}/sandbox/files?path=${encodeURIComponent(path)}`,
  );
}

export async function downloadSandboxFile(
  session_id: string,
  path: string,
): Promise<Blob> {
  return getDown(
    `/api/v1/sessions/${session_id}/sandbox/files/download?path=${encodeURIComponent(path)}`,
  );
}

export async function uploadSandboxFile(
  session_id: string,
  path: string,
  file: File,
) {
  const form = new FormData();
  form.append("path", path);
  form.append("file", file);
  return postUpload(`/api/v1/sessions/${session_id}/sandbox/files`, form);
}

export async function makeSandboxDir(session_id: string, path: string) {
  return post(`/api/v1/sessions/${session_id}/sandbox/files/mkdir`, { path });
}

export async function renameSandboxPath(
  session_id: string,
  from: string,
  to: string,
) {
  return post(`/api/v1/sessions/${session_id}/sandbox/files/rename`, {
    from,
    to,
  });
}

export async function deleteSandboxPath(session_id: string, path: string) {
  return del(
    `/api/v1/sessions/${session_id}/sandbox/files?path=${encodeURIComponent(path)}`,
  );
}
